// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKvqqTi3Cqv1ULrid_Mm5k2kYgPhmx258',
    appId: '1:67131694134:web:2c17ccf2849529f5f04c97',
    messagingSenderId: '67131694134',
    projectId: 'my-tinder-app-19d8a',
    authDomain: 'my-tinder-app-19d8a.firebaseapp.com',
    storageBucket: 'my-tinder-app-19d8a.appspot.com',
    measurementId: 'G-P7G1935YKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzRpSiKy2rJ2qtFA0jIThNJB3zVeUNuCI',
    appId: '1:67131694134:android:a9953e5a5d411e8df04c97',
    messagingSenderId: '67131694134',
    projectId: 'my-tinder-app-19d8a',
    storageBucket: 'my-tinder-app-19d8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00kdjHVsxiJ6PmQ2gMjqUKJDE-J_xNVM',
    appId: '1:67131694134:ios:dbff218a29e46a77f04c97',
    messagingSenderId: '67131694134',
    projectId: 'my-tinder-app-19d8a',
    storageBucket: 'my-tinder-app-19d8a.appspot.com',
    iosClientId: '67131694134-qdlmdfhblrs0qd4sfcnl2le7428pd0pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mniTenderFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00kdjHVsxiJ6PmQ2gMjqUKJDE-J_xNVM',
    appId: '1:67131694134:ios:dbff218a29e46a77f04c97',
    messagingSenderId: '67131694134',
    projectId: 'my-tinder-app-19d8a',
    storageBucket: 'my-tinder-app-19d8a.appspot.com',
    iosClientId: '67131694134-qdlmdfhblrs0qd4sfcnl2le7428pd0pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.mniTenderFlow',
  );
}
